//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gamescore")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: i32,
    pub updated_at: i32,    
    pub user_id: i64,
    pub game_type: String,
    pub game_level: i8,
    pub score: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
