//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "invitecode")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: i32,
    pub updated_at: i32,
    pub user_id: i64,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    pub is_used: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
