//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::friends::Entity as Friends;
pub use super::gamescore::Entity as Gamescore;
pub use super::invitecode::Entity as Invitecode;
pub use super::user::Entity as User;
