//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16
use serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;


#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, DeriveEntityModel, Eq, )]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: Option<i32>,
    pub updated_at: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
    pub role: String,
    pub referer: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub logo: String,
    #[serde(skip_serializing)]
    pub hashed_password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
